profiles/urls.py
from django.urls import path, include

from . import views

app_name='profiles'

urlpatterns=[

     path('user_profile/', views.user_profile, name='User_Profile'),

     path('login/', views.login_the_user, name='login'),

     path('register/', views.registration, name='register'),

     

]

theappdepo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
   # path('admin/', admin.site.urls),
]

profiles/models.py
from django.db import models

""" USER_PROFILE IMPORTS"""
from django.contrib.auth.models import AbstractUser
import secrets
import string
"""_.-._.-._.-._"""

class User_Profile(AbstractUser):
    
    """  ALTERING THE DJANGO BASE USER MODEL.  
    """
    email=models.CharField(max_length=40, blank=True, null=True, unique=True)

    ilovecookbooks_profile_pic=models.ImageField(upload_to='ilovecookbooks_profile_images',default="none")

    authentication_key= models.CharField(max_length=50, unique=True)

    is_verified = models.CharField(max_length=1, default='N')

    authentication_link= models.CharField(max_length=50, blank=True, null=True)
    
    def generate_unique_link(self):
        
        """  MAKES THE LINK TO COPY AND PASTE YOUR AUTHENTICATION KEY
        """
        
        link = ''.join(secrets.choice(string.ascii_letters + string.digits + string.punctuation) for _ in range (30))

        # The next few lines replace characters that would make a link fail to generate properly.

        link = link.replace('\\', str(secrets.randbelow(1000)))

        link = link.replace('/', str(secrets.randbelow(1000)))

        link = link.replace('"', str(secrets.randbelow(1000)))

        link = link.replace("'", str(secrets.randbelow(1000)))


    def save(self, *args, **kwargs):
        
        """  MAKES THE AUTHENTICATION KEY UPON USER CREATION .
             
             CALLS generate_unique_link

             also any other things we want to add upon user creation.
        """
        
        if not self.authentication_key:
            
            self.authentication_key = ''.join(secrets.choice(string.ascii_letters +string.digits + string.punctuation) for _ in range(30))
     
        if not self.authentication_link:
            
            self.authentication_link = self.generate_unique_link()

        super().save(*args,**kwargs)

profiles/forms.py
from django import forms

from .models import *


class Registration(forms.Form):

    username = forms.CharField(label='Username', max_length=100)

    email = forms.EmailField(label='Email')

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

profiles/views.py
from django.shortcuts import render,redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

from django.core.mail import send_mail
from django.urls import reverse

from .forms import *
from .models import *


User = get_user_model()

def home(request):

     greeting="The daily message is: 'Love conquers all!'"

     return render(request, 'home.html',{

          'greeting': greeting,})

def user_profile(request):

     greeting="User Profile!"

     return render(request, 'user_profile.html',{

          '': greeting,})

def login_the_user(request):

    if request.method == 'POST':

        username = request.POST['username']

        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:

            login(request, user)

            #return redirect('home_page:home_page')

        else:

            error_message = "Invalid credentials"

            return render(request, 'Error.html', {'error_message': error_message})

    else:

        return render(request, 'login.html')
    

def registration(request):

    """

    This creates a user model based on the User_Profile model which is the base User model extended.

    """

    if request.method == 'POST':

        form = Registration(request.POST)

        if form.is_valid():

            user_data = form.cleaned_data

            new_user = User_Profile.objects.create_user(

                username=user_data['username'],

                email=user_data['email'],

                password=user_data['password'],

            )

            try:

                registration_link = request.build_absolute_uri(

                    reverse('authenticate_user', args=[str(new_user.authentication_link)])

                )

                send_mail(

                    f"Welcome {new_user.username}",

                    f"Welcome to Flashcardzz!\n\n Here is how to get registered:\n\nBelow is your authentication key.\n\ncopy this:\n\n{new_user.authentication_key} \n\nClick the link below to complete your registration:\n\n{registration_link}",

                    "admin@ilovecookbooks.org",

                    [new_user.email],

                    fail_silently=False,

                )

            except:

                print("Sending an email failed")

            return render(request, 'login.html')

    else:

        form = Registration()

    return render(request, 'registration.html', {'form': form})

templates/experimental_playground/experimental_room_1.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Experiment Room 1</title>
</head>
<body>

     <h1>Experiment room 1</h1>
     
</body>
</html>

templates/flashcards/Error.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>

<body>
     <h1>We're Sorry!</h1>
     <p>There was an error.</p>

     <a href="{% url 'flashcards:flashcards_home' %}">Go Home</a>
</body>
</html>

templates/flashcards/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

     {%load static%}
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">


     <title>Document</title>
</head>
<body>

     <div class="text-container">
 
          <h1>About Us</h1>
  
      </div>

      <div class="main-content">

          <nav>
      
            <div class="row">

      
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
            </div>

          </nav>

     </div>

     
     <div class="text-container2">

          <h3>Mission Statement</h3>
      
          <p>I dream of a future where education is free for anyone who wants to learn. I have also laid out a step by step plan for getting college credits paid for here <a href="{% url 'clep'%}">CLEP info</a> </p>
          
          
     </div>
     
     
     <div class="text-container3">
     <p>I hope this website will grow into an education sharing platform. I will continue to add features that will help with learning. Some of the things I have in mind are:</p>

           
     <ul>

          <li><p>Adding a note taking word processor.</p></li>
          <li><p>A practice test generator</p></li>
          <li><p>and I want to add a GPT plugin to generate flash cards.</p></li>
          <li><p>If I monetize this, it will be on a donation basis. So don't worry, I will never demand money for service.</p></li>

     </ul>

      
      </div>

     
</body>
</html>

templates/flashcards/add_notes.html
<!DOCTYPE html>
<html lang="en">
<head>

     {%load static%}
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/add_note.css' %}">
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>
<body>


     <style>



     </style>


     
          {% block content %}


          <div class="text-container">

               <h1>Add Notes to {{ deck.title }}</h1>
       
           </div>

        



          <form method="post" action="{% url 'flashcards:add_notes' deck.id %}">

          {% csrf_token %}

          {{ form.as_p }}

          <button type="submit">Add Notes</button>

          </form>



          <a href="{% url 'flashcards:view_deck' deck.id %}">Back to Deck</a>

          {% endblock %}

</body>
</html>

templates/flashcards/clep_resources.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>

     {% load static %}


     <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
 
 
     <div class="text-container">
 
         <h1>CLEP</h1>
 
     </div>
</head>
<body>

     <div class="main-content">

          <nav>
      
            <div class="row">
      
              <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
      
            </div>

            <div class="row">
      
               <a href="https://modernstates.org/">Modern States</a>

               <a href="https://clep.collegeboard.org/clep-exams">College Board</a>
       
           </div>

          </nav>

     </div>

     <div class="text-container2">

          <h3>What is Clep?</h3>
      
          <p>To simply put this, CLEP is a way to earn college credits without the help of a college or university. Almost all colleges nowadays have a CLEP program, it's just never advertised. My best guess is that they would prefer if you paid them 10's of thousands of dollars. A CLEP exam costs about 100 dollars, but I will teach you how to get that fee waived, even if you fail!</p>
      
      </div>
      
      
      
      <div class="text-container3">
      
          <h3>Mission statement</h3>
      
          <p>The purpose of this page is to provide a clear cut path on how to earn your college credits, for FREE! I personally struggled with a low income, and low prospects for a higher education. That is why I am so passionate about helping others succeed in college, regardless of your income.</p>
      
      </div>
      
      
      <div class="text-container2">
      
      <h3>The good the bad and the ugly</h3>
      
      <p>I sense that you may be wondering, what is the catch? I respond, "There is no catch. Well maybe. Okay, It's complicated." CLEP alone will charge you 93 dollars, and then you have to usually pay around 15 to 20 dollars for testing fees to the testing center. That is a lot of money for a poor guy like me, so I did some research. The organization <a href="https://modernstates.org/">Modern States</a> will reimurse your test fee, AND the exam fee. In fact, it took me three attempts to pass the Western Civ I exam, and I was paid back for each exam in full. The only requirement is to finish 75% of their study guide for each exam. Personally, I skipped all the videos and just do the homework and final tests. [which is probably why I failed so many times]. What is awesome is that they have entire college textbooks hosted for free, and that they will reimburse a knucklehead like me!</p>
     </div>


     <div class="text-container3">
     <h3>The how to</h3>

     <p>From start to finish, here is a broad overview of the steps to take in order to get your college exam paid for.</p>

     
     <ul>

          <li><p>Take a look at this helpful FAQ page: <a href="https://modernstates.org/faq/">Frequently Asked Questions</a></p></li>

          <li><p>Search for your college <a href="https://clep.collegeboard.org/clep-college-credit-policy-search?gclid=CjwKCAiA04arBhAkEiwAuNOsIogRtm3xmS0nvzFjkYdwg4Umgjk2WjYXwbN6M2H8YEVF-l6mQFhHMRoCQ14QAvD_BwE&ef_id=CjwKCAiA04arBhAkEiwAuNOsIogRtm3xmS0nvzFjkYdwg4Umgjk2WjYXwbN6M2H8YEVF-l6mQFhHMRoCQ14QAvD_BwE:G:s&s_kwcid=AL!4330!3!653271134082!e!!g!!what%20colleges%20accept%20clep!1493550655!57249015763&gad_source=1">here</a> and see what clep credits they will accept.</p></li>

          <li><p> Call the college and request to speak with someone who handles CLEP. Ask them "What is the max ammount of CLEP credits I can use?"</p></li>

          <li><p>Create an account on <a href="https://modernstates.org/">modernstates.org</a> and enroll in a course that your college approves of.</li>
          
          <li><p>Follow the course and complete the 'check for understanding', 'homework', and 'final test'. You can google on your test >:]'</p></li>

          <li><p>Request a voucher here:<a href="https://modernstates.org/clep-voucher-request/">voucher</a></p></li>

          <li><p>Once you get your voucher. Register for your exam <a href="https://clep.collegeboard.org/clep-exams">here</a> and apply your voucher.</p></li>

          <li><p>Sign up to take your test at an approved testing facility: <a href="https://clep.collegeboard.org/clep-test-center-search">Test center searcher</a>. It will cost between 15-30 dollars, but Modern States will reimburse you. KEEP YOUR RECEIPT!!</a></p></li>

          <li><p>Once you take your test, request your test center reimbursement: <a href="https://modernstates.org/test-center-reimbursement/">Test Center Reimbursement</a></p></li>

          <li><p>Repeat this list for your next class!</p></li>
     </ul>

     </div>


     <div class="text-container2">
     
<h3>Good luck and final words!</h3>

<p>   I wish you the best of luck on finding your path. Keep in mind that CLEP credits do not effect your GPA. It is pass or fail. This can be to your advantage if there is a class that is a stain on your transcript. Retake the test with CLEP and if you pass, you can turn that C- into a pass! Then no one will know you did terrible, and watch your GPA rise! Last thing. I get very happy when I see that people are using my softwares. I would like you to create flashcards in our flashcard app. This will help someone else pass their exam, and it will make me very happy! Cheers!</p>

</div>
</body>
</html>

templates/flashcards/create_card.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Create Flashcard</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">

</head>

<body>

    <div class="text-container">

        <h1>Create Card</h1>

    </div>


    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
    
    
          </div>
    
        </nav>


    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create Card</button>

    </form>

</body>

</html>

templates/flashcards/create_deck.html
<!DOCTYPE html>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">




<html lang="en">

<head>

    <meta charset="UTF-8">

    <div class="text-container">

        <h1>Create Deck</h1>

    </div>

</head>

<body>


    <div class="main-content">

        <nav>
    
          <div class="row">
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
          </div>

        </nav>



    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create Deck</button>

    </form>


</body>

</html>

templates/flashcards/edit_card.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/create_deck.css' %}">


<div class="text-container">
 
     <h1>Edit Card</h1>

 </div>



<div class="main-content">
<form method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Save Changes</button>

</form>

</div>

templates/flashcards/edit_deck.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/edit_deck.css' %}">

    <title>Edit_Deck</title>

    
    <div class="text-container">

        <h1>Edit Deck</h1>

    </div>

</head>

<body>

    <div class="main-content">

        <nav>
    
          <div class="row">
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>
            <a href="{% url 'flashcards:flashcards_home' %}">Home</a>
          </div>

        </nav>


        <form method="post">

            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit" class="save_changes">Save Changes</button>

        </form>



        <form method="post">

            {% csrf_token %}

            {{ delete_deck_form.as_p }}

            <button type="submit" class="delete_button">Delete Deck</button>

        </form>


</body>
</html>

templates/flashcards/edit_note.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/add_note.css' %}">


<div class="text-container">
 
     <h1>Edit Note</h1>

 </div>


<div class="main-content">

<form method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Save Changes</button>

</form>

</div>

templates/flashcards/flashcards_home.html
<!DOCTYPE html>

<html lang="en">


    {% load static %}


    <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css.css' %}">


    <div class="text-container">

        <h1>Flashcardzz</h1>

    </div>


<body>

    {% if request.user.is_authenticated %}


    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:logout'%}">Log out</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:user_profile' request.user.pk %}">Your Profile</a>

            <a href="{%url 'flashcards:flashcards_home'%}">/flashcards</a>

            <a href="{% url 'home_page:home_page'%}">App Depo</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:clep'%}">CLEP</a>
    
          </div>
    
        </nav>


    {% else %}

    <div class="main-content">

        <nav>
    
          <div class="row">
    
            <a href="{% url 'flashcards:about_us'%}">About Us</a>
    
          </div>
    
          <div class="row">
    
            <a href="{% url 'flashcards:clep'%}">CLEP</a>
    
          </div>
    
        </nav>
    
    {% endif %}



    {% if request.user.is_authenticated %}

        <div class="hero">

        <p>Thank you for your support!</p>
            
        </div>
    {% else %}

        <div class="list-container">

        <div class="hero">

            <h2>Welcome to our platform!</h2>

            <ul>
      
            <li><p>Accelerate your learning with personalized flashcards.</li>

            <li><p> Create and share, then watch knowledge stick!</p></li>

            </ul>

            </div>

        </div>
       
        </div>

    {%endif%}


    
 
    
    </head>
    
    <body>
    
        <div class="grid-container">
    
            {% for category, decks in public_decks_by_category.items %}

            {% if decks%}
    
                <div class="grid-item">
    
                    <p>{{ category }}</p>
    
                    <ul>
    
                        {% for deck in decks %}
    
                            <li>
    
                                <a href="{% url 'flashcards:view_deck' deck.id %}">{{ deck.title }}</a>
    
                            </li>
    
                        {% endfor %}
    
                    </ul>
    
                </div>

            {%endif%}
    
            {% endfor %}
    
        </div>


      </br></br>
    
    
    

    </body>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
    

    <script src="{% static 'javascript.js' %}"></script>
    
    </html>
    
    

templates/home_page/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APP DEPO</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base_css/base_output.css' %}">
    <style>
        /* CSS styles specific to this HTML file */
        .image-container {
            position: relative;
            width: 100%;
            /* max-width: 400px; */ /* Remove max-width to allow grid columns to determine width */
            background-color: #ffffff00;
            border-radius: 8px;
            overflow: hidden; /* Ensure rounded corners apply correctly */
        }

        .image-header {
            position: relative;
            z-index: 2;
            padding: 10px;
            background-color: #fff; /* Adjust background color as needed */
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }

        .image-header h2 {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
            color: #333;
            text-align: center;
        }

        .image-header p {
            margin: 0;
            font-size: 14px;
            color: #666;
            text-align: center;
        }

        .image-overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(255, 255, 255, 0.9);
            display: flex;
            justify-content: center;
            align-items: center;
            opacity: 0;
            transition: opacity 0.3s ease-in-out;
            pointer-events: none;
        }

        .image-container:hover .image-overlay {
            opacity: 1;
        }

        .overlay-text {
            text-align: center;
            font-size: large;
            font-weight: bold;
            color: #333;
            padding: 10px;
        }
    </style>
    <!-- Tailwind CSS CDN (or include from your project) -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <h1 class="text-3xl font-bold mb-4">{{ greeting }}</h1>
        <div class="flex space-x-4 mb-4">
            <a href="{% url 'admin:index' %}" class="text-blue-500 hover:text-blue-700">Administrators</a>
            <a href="{% url 'profiles:register' %}" class="text-blue-500 hover:text-blue-700">Registration</a>
            <a href="{% url 'profiles:login' %}" class="text-blue-500 hover:text-blue-700">Log In</a>
            <a href="{% url 'profiles:User_Profile' %}" class="text-blue-500 hover:text-blue-700">User Profile</a>
            <a href="{% url 'experimental_playground:x1' %}" class="text-blue-500 hover:text-blue-700">Playground</a>
        </div>
        <!--
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 hover:bg-gray-100">
               <div class="image-container">
                <div class="image-header">
                    <h2>{{ ilovecookbooks.name }}</h2>
                </div>
                <a href="{% url 'ilovecookbooks:Main' %}">
                    <img src="{{ ilovecookbooks.image.url }}" alt="ilovecookbooks" class="mb-4 w-full rounded-lg shadow-lg">
                </a>
                <div class="image-overlay">
                    <div class="overlay-text">A cookbook library with the ability to save pages and make custom cookbooks.</div>
                </div>
            </div>

            <div class="image-container">
                <div class="image-header">
                    <h2>{{ flashcards.name }}</h2>
                </div>
                <a href="{% url 'flashcards:flashcards_home' %}">
                    <img src="{{ flashcards.image.url }}" alt="ilovecookbooks" class="mb-4 w-full rounded-lg shadow-lg">
                </a>
                <div class="image-overlay">
                    <div class="overlay-text">An app to make and share flashcards.</div>
                </div>
            </div>
            
        </div>
    </div>
    -->
</body>
</html>

templates/ilovecookbooks/Error.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>

<body>
     <h1>We're Sorry!</h1>
     <p>There was an error.</p>
</body>
</html>

templates/ilovecookbooks/base.html
<!DOCTYPE html>

<html lang="en">

<head>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'ilovecookbooks/css.css' %}">

    <div id="header">

        {% if user.is_authenticated %}
         <h1>Welcome {{user.username}}</h1>
        {% else %}
            <h1>Welcome!</h1>
        {% endif%}




    </div>

</head>

<body>

    <body onload="loadHeader()">

        <div id="header"></div>

    <div id="topbarbackcolor">

    <div class="flexbox-container">

        <div class="flexbox-item flexbox-item-1"><a href="{% url 'ilovecookbooks:foodblog' %}">Food Blog</a></div>

        <div class="flexbox-item flexbox-item-2"><a href="{% url 'ilovecookbooks:links' %}">Book Links</a></div>

        <div class="flexbox-item flexbox-item-1"><a href="{% url 'home_page:home' %}">App Depo</a></div>


        {% if user.is_authenticated %}

        {% with user_profile=user.userprofile %}
    
            <div class="flexbox-item flexbox-item-2">
    
                <a href="{%url 'ilovecookbooks:user_profile' user.pk%}">Your Stuff</a>            
    
            </div>
    
        {% endwith %}
    
        {% else %}
    
            <div class="flexbox-item flexbox-item-2">
        
                <a href="{% url 'profiles:login' %}">Login/Register</a>
        
            </div>
        
        {% endif %}
    
    

        <form id="search-form" action="{% url 'ilovecookbooks:search_results' %}" method="get">

            <input class="flexbox-item-entrybox" type="text" name="search_term" autocomplete="off" autofocus="true">

        </form>

        <form id="search-button" action="{% url 'ilovecookbooks:search_results' %}" method="get">

            <button class="flexbox-item-button" type="submit">Search</button>

        </form>

    </div>



    <div class="titlelabel">

    <h3>Recently Uploaded</h3>

    </div>



    <div class="carousel-container4">

        <div class="flexbox-container3">



            {% for book in recent %}

                <div class="book-item">

                    <strong>Title:</strong> {{ book.title }}<br>

                    <strong>Year:</strong> {{ book.year }}<br>

                    {% if book.cover_photo %}

                        <div class="book-image">

                            <!-- Use a local path for the image source -->

                            <img src="{{ book.cover_photo.url }}" alt="Page {{ page.pk }}">  

                        </div>

                    {% else %}

                        No image available<br>

                    {% endif %}

                    <a href="{% url 'ilovecookbooks:book_detail' pk=book.pk %}">View Details</a>

                </div>

            {% endfor %}



        </div>

    </div>



    <div class="titlelabel">

        <h3>All Books</h3>

    </div>

    

    <div class="carousel-container4">

        <div class="flexbox-container3">


            {% for book in all %}

                <div class="book-item">

                    <strong>Title:</strong> {{ book.title }}<br>

                    <strong>Year:</strong> {{ book.year }}<br>

                    {% if book.cover_photo %}

                        <div class="book-image">

                            <img src="{{ book.cover_photo.url }}" alt="Page {{ page.pk }}">  

                        </div>

                    {% else %}

                        No image available<br>

                    {% endif %}

                    <a href="{% url 'ilovecookbooks:book_detail' pk=book.pk %}" alt="Not Found">View Details</a>

                    

                </div>

            {% endfor %}


        </div>

    </div>

</body>




<script>

    document.addEventListener('DOMContentLoaded', function() {
    
    
    
        var searchForm = document.getElementById('search-form');
    
        var searchInput = searchForm.querySelector('[name="search_term"]');
    
        var searchButton = document.getElementById('search-button');
    
    
        searchForm.addEventListener('submit', function(event) {
    
            event.preventDefault(); // Prevent the form from submitting normally
    
            
    
            var searchTerm = searchInput.value.toLowerCase(); // Convert input to lowercase
    
            
    
            if (searchTerm.trim() !== '') {
    
                window.location.href = "{% url 'ilovecookbooks:search_results' %}?search_term=" + encodeURIComponent(searchTerm);
    
            }
    
        });
    
        searchButton.addEventListener('click', function(event) {
    
            event.preventDefault(); // Prevent the button from performing its default action
    
            searchForm.dispatchEvent(new Event('submit')); // Trigger the form submit event
    
        });
    
    });
    
    </script>




<body onload="loadHeader()">
    <div id="header"></div>
  
    <script>
      function loadHeader() {
        // No need to do anything here, the animation starts automatically
      }
    </script>

templates/ilovecookbooks/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Question</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

templates/profiles/login.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Registration</title>
</head>
<body>

     {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static profiles/User_Profile.css}">


     <h1>Login</h1>

     <a href="{% url 'profiles:register'%}">Register Here!</a>
     <a href="{% url 'password_reset'%}">Reset</a>
    <form method="post">

     {% csrf_token %}

     <label for="username">Username:</label>

     <input type="text" id="username" name="username" required><br>

     <label for="password">Password:</label>

     <input type="password" id="password" name="password" required><br>

     <button type="submit">Login</button>

     </form>
     
</body>
</html>